apiVersion: v1
kind: Pod
metadata:
  name: apisix-etcd-service-2
  namespace: apisix
spec:
  containers:
    - name: flask-emr
      image: surajn222/apisix:etcd
      ports:
      - containerPort: 5000
      command: [ "python3" ]
      args: [ "app.py", "--host=0.0.0.0", "--etcd_host='127.0.0.1'", "--etcd_port=2379" ]
